name: Creaci贸n de Nuevo Cliente

on:
  pull_request:
    branches:
      - main
    paths:
      - gestion_clientes/*

jobs:
  create-client:
    runs-on: ubuntu-latest

    steps:
    - name: Revisar c贸digo de creaci贸n de cliente
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Instalar dependencias
      run: |
        pip install -r gestion_clientes/requirements.txt

    - name: Ejecutar pruebas de creaci贸n de cliente
      run: |
        pytest gestion_clientes/test_creacion_cliente.py
